package com.xx88ll.seattle.taskmask;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "Assignees")
public class Assignee {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    String id;
    @DynamoDBAttribute
    String name;

    public  Assignee(){}
    public Assignee(String name){
        this.name=name;
    }
    public  String getId(){return this.id;}
    public String getName(){
        return this.name;
    }
    public void setId(String id){this.id=id;}
    public void setName(String name){
        this.name=name;
    }

}
