package com.xx88ll.seattle.taskmask;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
@DynamoDBTable(tableName = "Assignees")
@DynamoDBDocument
public class Assignee {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    String id;
    String name;
    public  Assignee(){}
    public Assignee(String name){
        this.name=name;
    }
   public  String getId(){return this.id;}
    public String getName(){
        return this.name;
    }
    public void setId(String id){this.id=id;}
    public void setName(String name){
        this.name=name;
    }

}
