package com.xx88ll.seattle.taskmask;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName = "Taskmask")
public class Task {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    String id;
    String title;
    String description;
    String status;
    @DynamoDBAttribute(attributeName="Assignee")
    Assignee assignee;

    @DynamoDBAttribute
    String imageUrl;

    @DynamoDBAttribute
    String thumbnailUrl;

    public Task(){}

    public Task(String title, String description, String status) {
        this.title = title;
        this.description = description;
        this.status = status;
    }
    public String getThumbnailUrl(){return this.thumbnailUrl;}
    public void setThumbnailUrl(String thumbnailUrl){this.thumbnailUrl=thumbnailUrl;}
    public String getImageUrl(){
        return this.imageUrl;
    }
    public void setImageUrl(String url){
        this.imageUrl=url;
    }
    public Assignee getAssignee(){return this.assignee;}
    public void setAssignee(Assignee assignee){this.assignee=assignee;}
    public String getId() { return id; }

    @DynamoDBAttribute
    public String getTitle() { return title; }
    @DynamoDBAttribute
    public String getStatus() { return status; }

    @DynamoDBAttribute
    public String getDescription() { return description; }

    public void setId(String id){ this.id = id; }
    public void setTitle(String title) { this.title = title; }
    public void setDescription(String description) { this.description = description; }
    public void setStatus(String status) { this.status = status; }
}
