package com.xx88ll.seattle.taskmask;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName = "Taskmask")
public class Task {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey()
    String id;
    String title;
    String description;
    String status;
    String assigneeid;
    public Task(){}

    public Task(String title, String description, String status) {
        this.title = title;
        this.description = description;
        this.status = status;
    }

    public String getId() { return id; }

    @DynamoDBAttribute
    public String getTitle() { return title; }
    @DynamoDBAttribute
    public  String getAssigneeid(){return assigneeid;};
    @DynamoDBAttribute
    public String getStatus() { return status; }

    @DynamoDBAttribute
    public String getDescription() { return description; }

    public void setId(String id){ this.id = id; }
    public void setAssigneeid(String assigneeid){this.assigneeid=assigneeid;}
    public void setTitle(String title) { this.title = title; }
    public void setDescription(String description) { this.description = description; }
    public void setStatus(String status) { this.status = status; }
}
